# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbplay < Formula
  desc ""
  homepage "https://github.com/dung28-td/dbplay"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dung28-td/dbplay/releases/download/v1.0.0/dbplay_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "a5d765cb822f1bbe72cadcf3b90654fe44b6bcf834cc0408bf8b4f403ba37147"

      def install
        bin.install "dbplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dung28-td/dbplay/releases/download/v1.0.0/dbplay_1.0.0_Darwin_arm64.tar.gz"
      sha256 "2fd7120be21f503108802f72d4833108ff60b53287469178179d11d880759b3d"

      def install
        bin.install "dbplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dung28-td/dbplay/releases/download/v1.0.0/dbplay_1.0.0_Linux_arm64.tar.gz"
      sha256 "50d13d2cb817878f4878860cc0fcb82f8b1d466539f6ef9341e6402470dd2ac0"

      def install
        bin.install "dbplay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dung28-td/dbplay/releases/download/v1.0.0/dbplay_1.0.0_Linux_x86_64.tar.gz"
      sha256 "ac33196bbb8ced86a45bfdb0d2a62cbcd33562a193690cda4bce07c7ee6cd362"

      def install
        bin.install "dbplay"
      end
    end
  end
end
